env:
  browser: true
  es2021: true
extends:
  - google
  - plugin:prettier/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  valid-jsdoc:
    - error
    - prefer:
        arg: param
        class: class
        return: returns
      requireParamType: false
      requireReturn: false
      requireReturnType: false
      requireReturnDescription: false
